addons:
  apt:
    packages:
    - python3.6-dev
    sources:
    - deadsnakes
deploy:
  on:
    condition: "$TRAVIS_PYTHON_VERSION == 2.7"
    repo: guykisel/robotframework-faker
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: H1dqNgZkfbSJ4ERULyniPhdKssB1L676PXkj3LDr6AW8gX/PTTe5eKwbnqQiV9Q86rScv3IJ10B8jHJ94GoMTMq/+8XZ+K4VEKoIGhmy31/3Q8faIdGcNgrCaDoyUj9ml1HP0/yr0sZjBEyEkomAb+HClrwKAOoDszyeTPgZJZM=
  provider: pypi
  user: guykisel
install:
- pip install -U pip
- pip install -r requirements-dev.txt
- python setup.py develop
language: python
python:
- '3.6'
- '3.4'
- '3.3'
- '2.7'
script:
- tox
